# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'CreditCardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreditCardList
 pod 'Kingfisher', '6.3.1'
 pod 'lottie-ios', '3.2.3'
 pod 'Firebase/Database'
 pod 'Firebase/Firestore'
 pod 'FirebaseFirestoreSwift' 
end
