# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '13.0'


target 'customTabBarController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SpeechBubble', '~>0.1.1'

  # Pods for customTabBarController

end
