# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift4HFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift4HFinal

pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit'

end
