# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftTest

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
pod 'RxDataSources'
pod 'SnapKit'

  target 'RxSwiftTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftTestUITests' do
    # Pods for testing
  end

end
